### ISSUE TITLE
no module torchaudio,please update the requirments.txt

### ISSUE THREAD

**Issue by seetimee** [MooreThreads/MooER#12]

**Comment by seetimee** [comment]
File "demo/app.py", line 80, in <module>
    this_model, this_tokenizer = mooer_model.init_model(
  File "/data2/stephen/语音/MooER/src/mooer/models/mooer_model.py", line 24, in init_model
    llm = setup_llm(model_config, train_config, peft_config)
  File "/data2/stephen/语音/MooER/src/mooer/models/mooer_model.py", line 140, in setup_llm
    elif train_config.use_peft:
AttributeError: 'NoneType' object has no attribute 'use_peft'

**Comment by seetimee** [comment]
The "moore-5k" is operating normally, but the "moore-80kv2" is not functioning properly.

**Comment by lzl-mt** [comment]
> File "demo/app.py", line 80, in this_model, this_tokenizer = mooer_model.init_model( File "/data2/stephen/语音/MooER/src/mooer/models/mooer_model.py", line 24, in init_model llm = setup_llm(model_config, train_config, peft_config) File "/data2/stephen/语音/MooER/src/mooer/models/mooer_model.py", line 140, in setup_llm elif train_config.use_peft: AttributeError: 'NoneType' object has no attribute 'use_peft'

can you check your src/mooer/configs/asr_config.py? You should set your own lora_dir, or start as `python app.py --lora_dir XXX`. The app.py script will not, by default, reach [this line](https://github.com/MooreThreads/MooER/blob/dd93d4016fcdd750f1438004486049fc2f19f4db/src/mooer/models/mooer_model.py#L140) because of the logic present [here](https://github.com/MooreThreads/MooER/blob/dd93d4016fcdd750f1438004486049fc2f19f4db/src/mooer/models/mooer_model.py#L123).

**Comment by lzl-mt** [comment]
e.g., `python demo/app.py --task asr --cmvn_path /configs/am.mvn --encoder_path /jfs/zhenlin.liang/model/paraformer-encoder.pth --llm_path /jfs/zhenlin.liang/model/Qwen2-7B-Instruct --adapter_path /root/MooER/output/save_models/adapter_project.pt --lora_dir /root/MooER/output/save_models/lora/new_llm`. you can check whether `loading lora_dir from XXX` in your log.

**Comment by seetimee** [comment]
After specifying the lora_dir and adapter_path clearly, it was fixed.
